# Generated by Django 4.1 on 2023-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.today.com%2Ffood%2Fhow-set-table-I70275&psig=AOvVaw1-9zeHAP5HdRRRtAxJnGTF&ust=1681480084085000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIibrsr_pv4CFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
